### PR TITLE
Move `mypy` configuration into `pyproject.toml`

### LINKED ISSUE #917: Move mypy configuration to pyproject.toml
Since version 0.900, mypy can be configured via the `tool.mypy` section in `pyproject.toml`.

### PR DESCRIPTION
**Pull request by yeskunall**
Hey! Thanks for this dope `cookiecutter` template. Let me know if I need to make any changes before this can be merged.

❤️

<hr />

Closes #917

### CODE REVIEW

**Comment by cjolowicz** [comment]
Sweet, thanks!

I'll merge the Dependabot update for mypy first, will ping you to rebase when that's done.

**Review by cjolowicz — COMMENTED** [review]
Sweet, thanks!

I'll merge the Dependabot update for mypy first, will ping you to rebase when that's done.

**Update:** It turns out that we need to update sphinx-click first, then click, then mypy (while installing types-click into the mypy session).

**Comment by cjolowicz** [comment]
@yeskunall Can you rebase on master? It's already on the latest mypy version.

**Comment by yeskunall** [comment]
@cjolowicz you move quickly! Just got off work to see this has already been merged and made part of a new release. Once again, thanks for your work on this. I actually first came across your project on [awesome-pyproject](https://github.com/carlosperate/awesome-pyproject#project-templates) and then went through your article. Very informative!

**Pull request merged**
