### PR TITLE
Add sphinx-click

### LINKED ISSUE #446: Add sphinx-click
[sphinx-click] is a Sphinx plugin that allows you to automatically extract documentation from a click-based application and include it in your docs.

[sphinx-click]: https://sphinx-click.readthedocs.io/en/latest/

This seems a good addition since we include both sphinx and click by default.

### PR DESCRIPTION
**Pull request by staticdev**
- Add sphinx-click dev dependency
- Add sphinx-click nox sessions
- Add new usage file to docs
- Add sphinx-click to docs/requirements.txt and the extension to docs/conf.py

Closes #446

### CODE REVIEW

**Comment by staticdev** [comment]
@cjolowicz I've added the basic of what I changed. I need to know what kind of instructions should we add in this case to cookiecutter documentation.

**Comment by cjolowicz** [comment]
@staticdev Thank you for doing the implementation work here, much appreciated! I decided to, at least temporarily, copy this to a new PR, #608. Due to the recent changes to the template, it was necessary to export your work to a project, rebase on the current master, and re-import it into the template. We can either sync it back into this PR, or I'll credit you using a `Co-Authored-By` line in #608 when merging.

**Comment by cjolowicz** [comment]
Ok, I had a closer look at this. I really like your decision to have a dedicated page for the command-line reference! My suggestion would be, however, to keep things simple and just link from the Usage section in the README.rst directly to the generated documentation. Here are the corresponding commits from #608:

- 49f9ae93d2f1f90d3bd1ccafd5bf03cd40580e66
- 0edd36493fa872c006e1bff6fe5d16e6b688b43f

As for the Cookiecutter documentation, I think we only need to update the feature list, the table of dependencies, and the overview of generated files:

- a2fd38c438ed0d60225a8167689b4b7893f0b87a
- f1cc08f8633d31701a93e10b647d5cbeb7092b29
- 137beba49c90cdc32359090e26b1b2399b996d02

What do you think about these suggestions?

In general, I avoid copying another contributor's work into a new PR; I only made an exception here due to the complicated rebase and import/export. So if you would like to continue the review with your own PR, that's very welcome and encouraged! If on the other hand, you'd simply like #608 to be merged, that's also cool and I'll make sure to credit you on the other PR.

To continue with your own PR, I would suggest to first hard-reset your branch to the rebased version on my branch (i.e. excluding the changes listed above), like this:

```sh
git checkout add-sphinx-click
git fetch origin retrocookie-pr/sphinx-click
git status  # important: make sure you have no uncommitted or un-pushed work before the next step
git reset --hard d7f1aea1fadbdcadf730224a8ecdfa08174a4dd0
git push --force-with-lease origin add-sphinx-click
```

**Comment by staticdev** [comment]
@cjolowicz since you had the effort of copying the commits we can close this one.

Very nice that you already changed the documentation, and you used a simpler way to import it. For me simpler is better. I like the changes!

**Comment by cjolowicz** [comment]
Superceded by #608 

Thanks @staticdev 👍

**Pull request closed without merging**
