### PR TITLE
Require click 8.x

### LINKED ISSUE #908: Projects created using Click 8.0
New major version is out. Might be nice to create new projects using it instead of 7.

### PR DESCRIPTION
**Pull request by staticdev**
Closes #908

### CODE REVIEW

**Comment by cjolowicz** [comment]
The version constraint already allows click 8. Or is this about disallowing click 7?

**Comment by staticdev** [comment]
> The version constraint already allows click 8. Or is this about disallowing click 7?

Yes, since you are creating a project with cookiecutter, what is the meaning of allowing click 7? I don't get it. Also, we stay in the same pattern as other dependencies so it is simpler to understand/maintain.

**Comment by cjolowicz** [comment]
It's relevant if you update an existing project, for example with cruft.

**Comment by cjolowicz** [comment]
Oh well, I guess project updates need to review and merge dependencies anyway.

**Review by cjolowicz — APPROVED** [review]

**Comment by staticdev** [comment]
BTW have you tried cruft @cjolowicz? I was looking for a good solution to update project based on updated cookiecutter, didn't find an easy one.

**Pull request merged**
