### PR TITLE
Added toml-check hook to pre-commit

### LINKED ISSUE #184: Add check-toml pre-commit
https://github.com/pre-commit/pre-commit-hooks#check-toml

### PR DESCRIPTION
**Pull request by staticdev**
Closes #184

### CODE REVIEW

**Comment by cjolowicz** [comment]
Thanks for the contribution 👍 🎉 

I'm working some more on the integration of Nox, pre-commit and Poetry, so it'll have to wait a bit. Not too long though I hope...

Would you like to update the docs as well? There is a section describing the pre-commit hooks. But I can also add it when I merge this PR.

**Comment by staticdev** [comment]
@cjolowicz =) I also changed the documentation.. I am testing dependabot to see if I can contribute with more automation on dependencies side. I saw a [video on automerging](https://www.youtube.com/watch?v=0ahRkhrOePo&list=PLbBkH8AQhXxHDEVFC6Fjoq7jX79Lb05RJ&index=31&t=900s) pull requests from dependabot.

**Comment by cjolowicz** [comment]
That's perfect for the documentation, thanks!

I just realized that we need to move your change from `.pre-commit-config.yaml` to  `{{cookiecutter.project_name}}//.pre-commit-config.yaml`... The top-level file belongs to the Cookiecutter infrastructure (which does not have TOML files). The stuff under `{{cookiecutter.project_name}}` is what actually goes into the generated project.

Interesting video, by the way.

**Comment by staticdev** [comment]
@cjolowicz My mistake! Just fixed.

**Pull request merged**
