### PR TITLE
WIP: Automerge workflow

### LINKED ISSUE #296: Suggestion: Add dependabot automerge workflow on Github Actions
I have an updated working version of the video I sent you here:
https://github.com/staticdev/django-pagination-bootstrap/blob/master/.github/workflows/dependabot.yml

### PR DESCRIPTION
**Pull request by staticdev**
Closes #296

### CODE REVIEW

**Comment by staticdev** [comment]
@cjolowicz I recreated my PRs with much less commits. I had to delete my fork since master was compromised and rebase from upstream wasn't working (I still struggle with rebases and remotes).

**Comment by staticdev** [comment]
@cjolowicz LGTM? I really find useful having dependabot PR automatically merged =p

**Comment by cjolowicz** [comment]
Sorry for letting this sit here for so long.

I must confess, I have doubts that this is a good fit for this template. It's no doubt very useful in many projects, but it makes strong assumptions about the way a project "ticks". You need to have a very thorough test suite to prevent upgrades that break your code. Even then, there is no guarantee nothing will break. And for some projects, merging PRs without review is a no-no, even for Dependabot.

Also I'm curious, I didn't understand if/how the workflow prevents merging when other checks failed?

**Comment by staticdev** [comment]
@cjolowicz you are right, I got my first automerged broken lib (https://github.com/staticdev/irpf-cei/commit/0d0dd50c5f472a5be30852f4ff1f435e647690d4) I will put this on draft until I make safer automerge passing all checks.

**Comment by cjolowicz** [comment]
Thanks for working on this @staticdev 

I'm closing this for the reasons mentioned [above](https://github.com/cjolowicz/cookiecutter-hypermodern-python/pull/401#issuecomment-665904339).

Please feel free to continue the discussion though.

**Pull request closed without merging**
