### PR TITLE
Add interrogate pre-commit hook

### LINKED ISSUE #247: Add interrogate
Add the official pre-commit hook for interrogate.

[interrogate] checks your code base for missing docstrings.

[interrogate]: https://interrogate.readthedocs.io/en/latest/

Do we keep flake8-docstrings (pydocstyle)? I think so.

### PR DESCRIPTION
**Pull request by paw-lu**
Adds [interrogate](https://interrogate.readthedocs.io/en/latest/) as a pre-commit hook. In addition documents the pre-commit hook and makes some opinionated choices in the config:

1. Set verbosity to 2 (This is the only mode that will surface the name of the function with the missing docstring)
2. Set coverage to 100%
3. Forces color to true (for GitHub actions output)

Closes #247.

### CODE REVIEW

**Comment by paw-lu** [comment]
I'll rebase later to fix the conflicts 😅.

**Comment by cjolowicz** [comment]
Thank you, this looks nice!

How does it compare to flake8-docstrings/pydocstyle? I'm wondering whether it makes sense to have both.

**Comment by paw-lu** [comment]
Good question!

As a tool interrogate focuses soley on docstring coverage. Where you can set coverage goals and more complex ignore conditions (exclude regex, exclude files, etc).

But, they way this is currently configured (check all files, 100% coverage), it's similar to pydocstyles `D1xx`s except that it also checks private functions/methods/classes/modules/etc. I integrated it to a project for exactly this reason—I was forgetting to document some private functions.

If you wanted to only have one I would definitley take pydocstyle, since it checks for much more than the simple existance of docstrings. If you don't want to enforce private docstring coverage, and want 100% public docstring coverage, than I don't think you would need interrogate at all.

Want to also mention that this was a backport from a project, so it took 0 additional work on my end, so you should feel no obligation to merge if we think it's too redundant for the template.

**Comment by paw-lu** [comment]
One more note on this PR. Interrogate can generate a badge—like coverage's which is used on the README in this project—but it's  generated as a local file.

So you would need something like a GitHub action to generate the svg badge, commit it, and push to the remote branch (which would require a GitHub token). [The GitHub action for interrogate has an example at the bottom.](https://github.com/marketplace/actions/python-interrogate-check)

This seemed like a bit much—both generating a commit and asking the user to create a GitHub token just for an svg icon, so I left it out for now.

**Comment by cjolowicz** [comment]
Cool, that's helpful info!

Overall, my tendency is to stay with just pydocstyle here. interrogate does look great, but it feels like having it on top of, or instead of, pydocstyle very much depends on the needs of the individual project. On the other hand, pydocstyle seems like a good baseline for any new (i.e. non-legacy) project.

(This PR is actually a nice howto and rationale for anyone wanting to integrate this template with interrogate. Wondering how to make this kind of information more visible... 🤔 )

**Comment by paw-lu** [comment]
> On the other hand, pydocstyle seems like a good baseline for any new (i.e. non-legacy) project.

Yeah that sounds good to me! Closing the issue to limit noise.

> (This PR is actually a nice howto and rationale for anyone wanting to integrate this template with interrogate. Wondering how to make this kind of information more visible... 🤔 )

This is a thought for another PR/issue, but maybe the docs could use a very general (not interrogate specific) _How to add another linter_ section detailing the basics (add dev dep via Poetry, add to pre-commit local hooks, add dependency to nox session, force color for GitHub action, etc).

**Comment by cjolowicz** [comment]
There's this:

- https://cookiecutter-hypermodern-python.readthedocs.io/en/stable/guide.html#adding-a-python-language-hook

For more specific howtos, a GitHub wiki page seems a good fit ("How to integrate with tool X"). It could contain the actual howto, or just link to issues, PRs, comments, discussions.

There's always going to be a need to extend the template beyond its current scope for individual projects, and it would be kind of neat to provide a space for that. Just thinking out loud here...

**Comment by paw-lu** [comment]
> There's this:
>
> - https://cookiecutter-hypermodern-python.readthedocs.io/en/stable/guide.html#adding-a-python-language-hook

That's exactly what I had in mind! 😅

> GitHub wiki page seems a good fit

Yeah that's a decent point. I've honestly always struggled to distinguish when something was appropriate for the wiki vs docs, but this seems like a good example for the looser structure of a wiki.

**Pull request closed without merging**
